### ISSUE TITLE
ledcAttachPin depreciated in new API

### ISSUE THREAD

**Issue by PaulMDUK** [t0nyz0/Bambu-Poop-Conveyor-ESP32#1]
Getting an error message when trying to compile (I also had to install PubSubClient library)

error: 'ledcSetup' was not declared in this scope
  501 |     ledcSetup(pwmChannel, freq, resolution);
      |     ^~~~~~~~~

error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
  502 |     ledcAttachPin(enable1Pin, pwmChannel);
      |     ^~~~~~~~~~~~~
      |     ledcAttach

exit status 1

Compilation error: 'ledcSetup' was not declared in this scope

**Comment by t0nyz0** [comment]
Sorry I know that is frustrating, because I was frustrated when [they deprecated this command](https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html#ledc) and broke all my ESP32 projects. 😅  All jokes aside, I should of mentioned this issue in my documentation. 


I'm working on moving my ESP32 projects over to the new API. I plan on the next version having the latest libraries to make this much smoother on installing, in the meantime you should be targeting a specific version. I'll see if I can get this project update with-in the next day or so.

**These two are out of date:
Board manager > ESP32 > Needs version 2.0.1.x
Library manager > ArduinoJson > Needs version 6.21.5**

### Screenshots

> Target **ESP32 2.0.1.x**
Board manager:
<img width="222" alt="image" src="https://github.com/user-attachments/assets/6ec65f76-a0b9-4895-9d0b-9fb9de48600b">

Libraries installed:
<img width="219" alt="image" src="https://github.com/user-attachments/assets/078d6f92-dea9-4a58-acab-9eb89c2d67fb">

**Comment by PaulMDUK** [comment]
Thanks a lot, reverting to older version has fixed that issue, now just need to find a more wifi reliable ESP32 board!

Your wiring diagram seems to not match the code either - ie.  Diagram states yellow+ into gp19 and green+ into gp18, however,  the code states the opposite.  Red appears to be in gp2 on diagram, but again, gp4 in code.

How does the motor enable pin connect to the motor controller too?  It states gp15 to the enable pin, but this is a jumper?

I also note from some of your images, there is a ground in pin2/gnd to the plug?

Sorry for all the questions, this is all new to me, but a lot of fun!

**Comment by t0nyz0** [comment]
I actually just fixed the code so that it will use the newer libraries. Those changes will be in 1.2.8 when I push it out. I'm testing right now. 

Oh wow - you are right about the diagram, I will fix that asap. Thank you for pointing those out. I cant believe I have not noticed that. 

> How does the motor enable pin connect to the motor controller too? It states gp15 to the enable pin, but this is a jumper?

You kinda just have to cram a wire in there with the jumper attached, this is not idea but I havent found a better way of doing it. I used a little hot glue to hold it in place.

> I also note from some of your images, there is a ground in pin2/gnd to the plug?

Yes, looks like thats missing on the diagram. I'll fix that as well.
